name:  ascii_tables
version: 1.0.2
description: Creates ascii based tables from collections.
author: Juan Simon <juan.simon@gmail.com>
homepage: https://github.com/lord-otori/ascii_tables

dependencies:
  unittest: 0.8.5